version: '3'
services: 
    cdmserver:
        ports:
        - "8080:8080" 
        env_file:
        - ./cdm-server.env
        restart: unless-stopped 
        volumes:
        # recommended settings for production
        - type: bind
          source: /var/lib/cdmserver
          target: /data
        - type: bind
          source: /var/log/cdmserver
          target: /log/cdmserver
  
